opt_in_rules:
- force_unwrapping
- force_cast
- force_try
#Temporary hide all these errors
disabled_rules:
- line_length
- type_name
- variable_name
- cyclomatic_complexity
- nesting
- shorthand_operator
- trailing_whitespace
- for_where
- statement_position
- colon
- type_body_length
- operator_whitespace
- unused_optional_binding
- vertical_whitespace
- function_body_length
- file_length
- syntactic_sugar
- empty_parentheses_with_trailing_closure
excluded:
- Carthage
- tun2socks
- test

force_unwrapping: error
force_cast: error
force_try: error
